#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Walkies_Android.Resource", IsApplication=true)]

namespace Walkies_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000d
			public const int DogButton1 = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int DogButton2 = 2130968592;
			
			// aapt resource value: 0x7f040013
			public const int DogButton3 = 2130968595;
			
			// aapt resource value: 0x7f040022
			public const int DogButton4 = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int DogButton5 = 2130968607;
			
			// aapt resource value: 0x7f040025
			public const int DogButton6 = 2130968613;
			
			// aapt resource value: 0x7f04001c
			public const int DogButton7 = 2130968604;
			
			// aapt resource value: 0x7f040016
			public const int DogButton8 = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int DogButton9 = 2130968601;
			
			// aapt resource value: 0x7f040024
			public const int DogDIstance4 = 2130968612;
			
			// aapt resource value: 0x7f04000f
			public const int DogDistance1 = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int DogDistance2 = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int DogDistance3 = 2130968597;
			
			// aapt resource value: 0x7f040021
			public const int DogDistance5 = 2130968609;
			
			// aapt resource value: 0x7f040027
			public const int DogDistance6 = 2130968615;
			
			// aapt resource value: 0x7f04001e
			public const int DogDistance7 = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int DogDistance8 = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public const int DogDistance9 = 2130968603;
			
			// aapt resource value: 0x7f04000e
			public const int DogName1 = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int DogName2 = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int DogName3 = 2130968596;
			
			// aapt resource value: 0x7f040023
			public const int DogName4 = 2130968611;
			
			// aapt resource value: 0x7f040020
			public const int DogName5 = 2130968608;
			
			// aapt resource value: 0x7f040026
			public const int DogName6 = 2130968614;
			
			// aapt resource value: 0x7f04001d
			public const int DogName7 = 2130968605;
			
			// aapt resource value: 0x7f040017
			public const int DogName8 = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int DogName9 = 2130968602;
			
			// aapt resource value: 0x7f04002d
			public const int Logout = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int Map = 2130968622;
			
			// aapt resource value: 0x7f040029
			public const int PageNumber = 2130968617;
			
			// aapt resource value: 0x7f04002c
			public const int Profile = 2130968620;
			
			// aapt resource value: 0x7f04000a
			public const int SearchFilter = 2130968586;
			
			// aapt resource value: 0x7f040028
			public const int back = 2130968616;
			
			// aapt resource value: 0x7f040007
			public const int button1 = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int editText1 = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int editText2 = 2130968579;
			
			// aapt resource value: 0x7f04002a
			public const int forward = 2130968618;
			
			// aapt resource value: 0x7f04000b
			public const int gridLayout1 = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout1 = 2130968580;
			
			// aapt resource value: 0x7f04002b
			public const int linearLayout2 = 2130968619;
			
			// aapt resource value: 0x7f04000c
			public const int linearLayout3 = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int linearLayout4 = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int switch1 = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textView2 = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int textView3 = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int textView4 = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Shelter = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
